### ISSUE TITLE
May I ask how can this be used?

### ISSUE THREAD

**Issue by abdojapan** [AssetRipper/GuidUpdater#31]
Hi,

I have taken a look at the source and it seems to take 2 parameters, one for old asset directory and the other for new asset directory.

I suppose that after assetripper export finished, the project is duplicated, and the 'new' one should remove the scripts for textmeshpro for example and import the package for it.

Then run the application with the 'old' one that is intact after exporting and the 'new' one with has the package imported and the decompiled textmeshpro scripts removed, right?

That didn't seem to work.

Thanks for advance.

**Comment by ds5678** [comment]
Hi. I don't currently have any guides, and I don't plan on making this GitHub issue into one. However, if you have **specific** questions, I might be willing to answer them.

**Comment by abdojapan** [comment]
Thank you, I think I figured it out and it worked.

I imported the packages to the project, then set the new folder to the packages cache folder and the old folder to the Assets folder and it worked.
Of course I had to add a lot of exception handling, but it worked in the end.
